import type {NextPage} from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {Button} from "@fluentui/react-northstar";
import {signIn} from "next-auth/react";

const Home: NextPage = () => {
    const onClickSignIn = () => signIn();
    return (
        <div className={styles.container}>
            <Head>
                <title>Flash Card App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.logo}>{"><"}</div>
                <div className={styles.title}>Flashcard App</div>
                <Button onClick={onClickSignIn}>Login</Button>
            </main>
            <footer className={styles.footer}>
                <div>
                    created by eyupdalan
                </div>
                <div>
                    github
                </div>
            </footer>
        </div>
    )
}

export default Home
